FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV REFRESH_MINUTES=2
ENV KLINE_REFRESH_MINUTES=180
ENV KLINE_BATCH_SIZE=2
ENV KLINE_TOP_N=200
ENV FORCE_REFRESH=false
ENV REQUEST_TIMEOUT_SECONDS=12
ENV API_BASE_INTERVAL=2.5
ENV API_MAX_INTERVAL=15.0
ENV SECONDARY_API_INTERVAL=1.0
ENV CIRCUIT_BREAKER_THRESHOLD=4
ENV CIRCUIT_BREAKER_COOLDOWN=180

EXPOSE 8080

CMD ["sh", "-c", "uvicorn main_optimized:app --host 0.0.0.0 --port ${PORT:-8080}"]
