FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV REFRESH_MINUTES=2
ENV KLINE_REFRESH_MINUTES=180
ENV KLINE_BATCH_SIZE=2
ENV KLINE_TOP_N=80
ENV FORCE_REFRESH=false
ENV REQUEST_TIMEOUT_SECONDS=12
ENV API_BASE_INTERVAL=1.2
ENV API_MAX_INTERVAL=8.0
ENV SECONDARY_API_INTERVAL=0.45
ENV CIRCUIT_BREAKER_THRESHOLD=4
ENV CIRCUIT_BREAKER_COOLDOWN=180

EXPOSE 8080

CMD ["sh", "-c", "uvicorn main_optimized:app --host 0.0.0.0 --port ${PORT:-8080}"]
